# theme = "ayu_dark"
theme = "everforest_dark"

[editor]
auto-format = true
auto-save = true
color-modes = true
completion-replace = true
cursorline = true
line-number = "relative"
mouse = false
true-color = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
git-ignore = false
hidden = false

[editor.indent-guides]
character = "┊" # Some characters that work well: "▏", "┆", "┊", "╎"
render = true
skip-levels = 0

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.soft-wrap]
enable = true
max-indent-retain = 40
max-wrap = 10          # increase value to reduce forced mid-word wrapping

[editor.statusline]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"

[keys.normal]
a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]

H = ":buffer-previous"
L = ":buffer-next"

[keys.normal.g]
q = ":bc"
Q = ":bc!"
R = ":config-reload"

[keys.normal.y]
y = ["extend_to_line_bounds", "yank"]


