# theme = "ayu_dark"

theme = "everforest_dark"

[editor]
auto-format = true
auto-save = true
color-modes = true
completion-replace = true
cursorline = true
end-of-line-diagnostics = "hint"
idle-timeout = 0
line-number = "relative"
mouse = false
true-color = true

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
git-ignore = false
hidden = false

[editor.indent-guides]
character = "┊" # Some characters that work well: "▏", "┆", "┊", "╎"
render = true
skip-levels = 0

[editor.lsp]
# auto-signature-help = false
display-messages = true

[editor.soft-wrap]
enable = true
max-indent-retain = 40
max-wrap = 10          # increase value to reduce forced mid-word wrapping

[editor.statusline]
mode.insert = "I"
mode.normal = "N"
mode.select = "S"

[keys.normal]
# make a and i behavme more like i expect
a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]
# make escape a global collapse selection that works in place of esc/,/;
esc = ["collapse_selection", "keep_primary_selection"]
# Select line above
X = "extend_line_above"
H = ":buffer-previous"
L = ":buffer-next"
# remap gw to enter
"ret" = "goto_word"
