[language-server.nixd]
command = "nixd"

[[language]]
name = "nix"
language-servers = ["nixd"]

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports"}
language-servers = ["gopls"]

[language-server.gopls.config]
"ui.diagnostic.analyses" = { "nilness" = true, "unusedparams" = true, "unusedwrite" = true }
