colors:
  body: none
  date: black
  tags: yellow
  title: cyan
default_hour: 9
default_minute: 0
editor: "hx"
encrypt: false
highlight: true
indent_character: "|"
journals:
  default:
    journal: ~/CloudDocs/Obsidian/journal.txt
linewrap: 79
tagsymbols: "#@%"
template: false
timeformat: "%F %r"
version: v4.2.1
