"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[aliases]
"s" = ["show", "--name-only"]
"l" = ["log", "-r ::", "--limit", "20"]

[user]
name = "Zach Thieme"
email = "zach@techsage.org"

# [templates]
# log = "builtin_log_oneline"

[ui]
paginate = "never"
default-command = "log"

